# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50286f8b8db531629a18259abe42486f5ae8420c1ac51102e327c6bd8c97740bc8a4a74a060a71d85ce0070c646dcc2949e8161a8cd5247eb0307be65cc4e00

test:
  secret_key_base: 139a4bcda1bf1940bf9d706973bb19cf94e4cb00e49e3ec868c35631ce96f0e388057fbdc130703c8d23f4d89c60b2e35db9e9d2ea3341a253d46df0b3fb80ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
